### PR TITLE
New THT heatsink - SK29-25S

### PR DESCRIPTION
**Pull request by mpkopec**
THT heatsink available on TME - http://www.tme.eu/en/details/sk29-25s/radiators/

### CODE REVIEW

**Comment by michal777** [comment]
There are some broken rules: 6.3, 6.5, 6.6, 6.7, 10.2

**Comment by evanshultz** [comment]
@mpkopec 
This PR is quite old and the rules for footprints have changed since then. You can see the results of the rules checker above and there are a number of things to be done so this PR can be merged. Are you able to make the changes? Thanks again for contributing to KiCad!

**Comment by mpkopec** [comment]
Hi, I think I will be able to correct it, but maybe at the end of next week, I'm quite flooded right now.

**Comment by evanshultz** [comment]
@mpkopec Great! Thank you. We'll look for your update soon.

**Comment by SchrodingersGat** [comment]
@mpkopec I am closing this issue as we transfer footprints to the new library.

Please resubmit this to https://github.com//kicad/kicad-footprints

Thanks :)

**Pull request closed without merging**
