### PR TITLE
Upload AAVID TV5G heatsink footprint

### PR DESCRIPTION
**Pull request by tk5ep**
AAVID TV5G model heatsink TO220 horizontal footprint

[http://www.aavid.eu/products/standard/tv5g](url)
tv5g_hor

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi and thanks for your contribution. there are some things to change, before we can merge:
1. please remove the TO-220 housing from the footprint (keep the mounting hole). Then the complete thing is combined from an appropriate TO-220 footprint and this footprint. This way one can also use different packages (e.g. TO.220-5, ...) in together with this heatsink.
2. Please add an outline drawing of the heatingsink to the F.Fab-layer

Thanks,
JAN

**Comment by tk5ep** [comment]
Hi Jan,

If i remove the TO220 hosing, how will the model be aligned with the component holes ? Only by the mounting hole ?

How should the F.Fab layer drawing be ? Along the F.Crtyd or along the F.Silks ? I'd prefer the first one as it is a lot of drawing for the second one... ;-) 

For what part of the libraries are you responsible ?

Thanks,

**Comment by jkriege2** [comment]
ad 1: Yes by the mounting hole should be enough ... I think also you don't need to have the mounting hole here, as it is already a part of the TO-220 footprint. Simply make concentric circles (on F.Fab with the exact 4mm diameter and on F.SilkS with a bit larger diameter of say 4.5mm). then when laying out the PCB you can simply move the TO-220 to where it should be. In any other case we would need a series of different footprints (e.g. for different TO-220-variants, TO-126, ...) for each and every heatsink, which would be a real heap of work and unmanageable in the end.

ad 2: The F.Fab-layer should contain the EXACT outline of the package and silkscreen should contain a reasonable drawing that is visible AFTER assembly of the PCB. See http://kicad-pcb.org/libraries/klc/#f7

ad 3: I'm one of the librarians ... we don't really have fixed responsibilities, so I'm looking here and there at non-yet-looked-at PRs and give my comments, if I feel I know a bit about the topic ;-) Why do you ask?

Best,
JAN

**Comment by tk5ep** [comment]
Hi Jan,

Would that be OK ?

BTW, last time i PR, i got this KLC error

could not parse module: //home/travis/build/KiCad/Heatsinks.pretty/Heatsink_Aavid-TV5G_TO220_Horizontal.kicad_mod
Error: list index out of range

What does it mean ?

tv5g

**Comment by poeschlr** [comment]
About the parse error:
If the module opens in kicad without problems then it might be a bug in the test scripts.

**Comment by jkriege2** [comment]
yes, looks good, please move the courtyard closer to the heatsink ... it should be 0.25mm offset from the heatink.

Thanks,
JAN

**Comment by tk5ep** [comment]
I left it where it was englobing the transistot pads.
I will move it and upload it

Thanks,
Patrick

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Comment by tk5ep** [comment]
OK Jan,

Would it make sense to draw the same heatsink in the vertical position ?
If yes, how without any mounting hole, how can we position it versus the transistor ?

Patrick

**Pull request merged**
